baseURL = 'https://Otaru049.github.io/'
locale = 'zh-cn'
title = 'OTARU_049'
theme = 'ananke'

[params]
custom_css = ["custom.css"]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Post"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Tutorial"
  url = "/tutorials/"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4